### ISSUE TITLE
cannot run in win7

### ISSUE THREAD

**Issue by sharkocha** [vyrus001/go-mimikatz#5]
i compiled go-mimikatz in linux to exe and try to run it in windows 7, here is the error:

```
...
...
2021/06/23 20:37:29 Hash for kernel32.dll : AddVectoredExceptionHandler = 458312d8769b4c38
2021/06/23 20:37:29 Hash for kernel32.dll : RemoveVectoredExceptionHandler = ef2b49c257da8abb
2021/06/23 20:37:29 encrypting instance
2021/06/23 20:37:30 Leaving.
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x1535976]

goroutine 1 [running]:
runtime.throw(0x15bb61d, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x79 fp=0xc0000d3af8 sp=0xc0000d3ac8 pc=0x13192d9
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:245 +0x2d6 fp=0xc0000d3b50 sp=0xc0000d3af8 pc=0x132d856
golang.org/x/sys/windows.UTF16PtrToString(0x6e0055c0000139, 0x0, 0x0)
        /home/lfish/go/pkg/mod/golang.org/x/sys@v0.0.0-20200828194041-157a740278f4/windows/syscall_windows.go:129 +0x36 fp=0xc0000d3ba8 sp=0xc0000d3b50 pc=0x1535976
github.com/C-Sto/BananaPhone/pkg/BananaPhone.stupidstring.String(...)
        /home/lfish/go/pkg/mod/github.com/!c-!sto/!banana!phone@v0.0.0-20200831032744-0f0431a7d400/pkg/BananaPhone/internal.go:97
github.com/C-Sto/BananaPhone/pkg/BananaPhone.GetModuleLoadedOrder(0x1a, 0xc00078e000, 0xc00000e570, 0x20, 0xc000094998)
        /home/lfish/go/pkg/mod/github.com/!c-!sto/!banana!phone@v0.0.0-20200831032744-0f0431a7d400/pkg/BananaPhone/functions.go:37 +0x58 fp=0xc0000d3be8 sp=0xc0000d3ba8 pc=0x1541eb8
github.com/C-Sto/BananaPhone/pkg/BananaPhone.InMemLoads(0x1595b80, 0xc000004198, 0xc0000d3cf8)
        /home/lfish/go/pkg/mod/github.com/!c-!sto/!banana!phone@v0.0.0-20200831032744-0f0431a7d400/pkg/BananaPhone/functions.go:55 +0xc7 fp=0xc0000d3c60 sp=0xc0000d3be8 pc=0x1541fc7
github.com/C-Sto/BananaPhone/pkg/BananaPhone.NewBananaPhoneNamed(0x2, 0x15bc493, 0x9, 0x15c451e, 0x1d, 0x0, 0x0, 0x2eb4a0)
        /home/lfish/go/pkg/mod/github.com/!c-!sto/!banana!phone@v0.0.0-20200831032744-0f0431a7d400/pkg/BananaPhone/bananaphone.go:64 +0x71 fp=0xc0000d3d78 sp=0xc0000d3c60 pc=0x15411d1
github.com/C-Sto/BananaPhone/pkg/BananaPhone.NewBananaPhone(...)
        /home/lfish/go/pkg/mod/github.com/!c-!sto/!banana!phone@v0.0.0-20200831032744-0f0431a7d400/pkg/BananaPhone/bananaphone.go:40
main.main()
        /home/lfish/Downloads/go-mimikatz/main.go:84 +0x52a fp=0xc0000d3f88 sp=0xc0000d3d78 pc=0x154294a
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000d3fe0 sp=0xc0000d3f88 pc=0x131baf6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000d3fe8 sp=0xc0000d3fe0 pc=0x134c661
```

**Comment by vyrus001** [comment]
this is an issue with bananaphone and it not supporting windows 7, that said, golang does not officially support windows 7 either, but ill take a look at this when i get a chance
